config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tweets#index"

  authenticated :user do
    resources :tweets, only: [:new, :create, :edit, :update, :destroy]
    post '/tweets/:id/favorite', to: 'tweets#favorite', as: :favorite
    delete '/tweets/:id/favorite', to: 'tweets#unfavorite', as: :unfavorite

    post '/user/:id/follow', to: 'users#follow', as: :follow
    delete '/user/:id/follow', to: 'users#unfollow', as: :unfollow
  end

  # Separate because it doesn't require authentication
  resources :tweets, only: [:index]

  # /users/:id conflicts with Devise
  get '/user/:id', to: 'users#show', as: :user
  get '/user/:id/mentions', to: 'users#mentions', as: :mentions

end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id                :integer          not null, primary key
#  message           :string
#  link              :string
#  user_id           :integer          not null
#  reply_to_id       :integer
#  original_tweet_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Tweet < ApplicationRecord

  # ActiveRecord relationships
  belongs_to :user, inverse_of: :tweets
  # Direct replies
  belongs_to :reply_to, class_name: 'Tweet', 
                        inverse_of: :direct_replies, 
                        optional: true
  has_many :direct_replies, class_name: 'Tweet', 
                            inverse_of: :reply_to,
                            foreign_key: :reply_to_id
  # Ancestor tweet, used to avoid reddit problem of having to iterate every level of replies to build a thread
  belongs_to :original_tweet, class_name: 'Tweet', 
                              inverse_of: :all_replies, 
                              optional: true
  has_many :all_replies, class_name: 'Tweet', 
                         inverse_of: :original_tweet,
                         foreign_key: :original_tweet_id
  # Favorites
  has_many :favorites, inverse_of: :tweet
  has_many :favorited_users, through: :favorites,
                             source: :user 
  has_and_belongs_to_many :mentioned_users, class_name: 'User',
                                     join_table: 'mentions',
                                     inverse_of: :mentions

  # Scopes
  scope :feed, -> { order(created_at: :desc).includes(:user) }

  # Validations
  validates :user, presence: true

  # Class methods

  # Instance methods

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  # Show a feed of tweets
  def index
    @tweets = Tweet.all.feed
  end

  # New tweet form
  def new
  end

  # Save new tweet
  def create
    # Injection risk, don't do this in production!
    @tweet = TweetCreator.run(params[:tweet], current_user)

    if @tweet.errors.any?
      respond_to do |format|
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
        format.html { redirect_to root_path, alert: "Tweet could not be saved" }
      end
    else
      respond_to do |format|
        format.json { render json: @tweet }
        format.html { redirect_to root_path, notice: "Tweet was saved" }
      end
    end

  end

  # Edit tweet form
  def edit
  end

  # Save updated tweet
  def update
  end

  # Delete tweet
  def destroy
  end

  # Favorite a tweet
  def favorite

    @tweet = Tweet.find(params[:id])
    current_user.favorite_tweet(@tweet)

    redirect_to params[:redirect] || root_path

  end

  # Unfavorite a tweet
  def unfavorite

    @tweet = Tweet.find(params[:id])
    current_user.unfavorite_tweet(@tweet)

    redirect_to params[:redirect] || root_path

  end

end

app/views/tweets/_form.html.erb
<div class="row">
  <div class="col-lg col-md"></div>
  
  <div class="col-lg col-md">
    <%= form_for :tweet, url: tweets_path do |f| %>
      
      <div class="form-group">
        <%= f.text_field :message, placeholder: "What's happening?", class: "form-control" %>
      </div>

      <%= f.submit "Tweet", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="col-lg col-md"></div>
</div>

app/views/tweets/_tweet.html.erb
<div class="list-group-item">
  <div class="row">
    <div class="col-lg-6 col-md-6">
      <a class="col-lg col-md" href="<%= user_path(tweet.user) %>"><%= tweet.user.name %></a>
      <span class="col-lg col-md"><%= tweet.user.screen_name %></span>
      <span class="col-lg col-md"><%= tweet.created_at.strftime('%H:%M %b %-d, %Y') %></span>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 col-md-2"></div>
    <div class="col-lg col-md"><%= tweet.message %></div>
  </div>


  <% if user_signed_in? %>
    <div class="row">
      <% if current_user.favorited_tweet?(tweet) %>
        <%= button_to "Unfavorite", unfavorite_path(tweet, redirect: request.original_url), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= button_to "Favorite", favorite_path(tweet, redirect: request.original_url), method: :post, class: "btn btn-secondary" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <%= render 'form' %>
<% end %>

<div class="list-group">
  <%= render @tweets %>
</div>