config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tweets#index"

  authenticated :user do
    resources :tweets, only: [:new, :create, :edit, :update, :destroy]
    post '/tweets/:id/favorite', to: 'tweets#favorite', as: :favorite
    delete '/tweets/:id/favorite', to: 'tweets#unfavorite', as: :unfavorite

    post '/user/:id/follow', to: 'users#follow', as: :follow
    delete '/user/:id/follow', to: 'users#unfollow', as: :unfollow
  end

  # Separate because it doesn't require authentication
  resources :tweets, only: [:index]

  # /users/:id conflicts with Devise
  get '/user/:id', to: 'users#show', as: :user
  get '/user/:id/mentions', to: 'users#mentions', as: :mentions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Make sure users save with all parameters
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :screen_name])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Twit</a>

  <% if user_signed_in? %>
    <%= link_to "My Profile", user_path(current_user), class: "nav-item nav-link" %>
    <%= link_to "My Mentions", mentions_path(current_user), class: "nav-item nav-link" %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
  <% else %>
    <%= link_to "Log In", new_user_session_path, class: "nav-item nav-link" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %>
  <% end %>
</nav>